apiVersion: 1
deleteDatasources:
  - name: Jaeger
    orgId: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: Open trace
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      streamingEnabled:
        search: true
        metrics: true
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: -10m
        spanEndTimeShift: 10m
        tags:
          - key: service.name
            value: job
        queries:
          - name: Request rate by route
            query: sum by (route) (rate(http_server_requests_total{$$__tags}[1m]))
          - name: p99 latency by route
            query: histogram_quantile(0.99, sum by (le, route) (rate(http_server_duration_seconds_bucket{$$__tags}[1m])))
